//
//  ConcordAction.swift
//  ConcordUI
//
//  Created by Steve Sheets on 8/16/26.
//
//  Defines portable ConcordUI action events and internal dispatch support.
//

// MARK: - Action Type

/// Describes the kind of user action generated by a ConcordUI element.
public enum ConcordActionType: Hashable, Sendable {
    /// A button was activated by the user.
    case buttonActivate

    /// An editable element changed its value.
    case valueChanged
}

// MARK: - Action Event

/// Information describing an action generated by a ConcordUI element.
public struct ConcordActionEvent {
    /// Kind of action that occurred.
    public let type: ConcordActionType

    /// Element that generated the action.
    public let element: ConcordElement

    /// Creates an action event.
    public init(type: ConcordActionType, element: ConcordElement) {
        self.type = type
        self.element = element
    }
}

/// Closure used to handle a ConcordUI action.
public typealias ConcordActionClosure = (ConcordActionEvent) -> Void

// MARK: - Internal Dispatch

/// Internal routing endpoint used by elements without exposing application hierarchy to them.
internal protocol ConcordActionDispatching: AnyObject {
    func dispatchAction(_ event: ConcordActionEvent)
}

/// Internal notification endpoint used when an element's presentation model changes.
internal protocol ConcordElementChangeDispatching: AnyObject {
    func elementDidChange(_ element: ConcordElement)
}
